### PR TITLE
Added Yahoo.Symbol(..).GetJsonAsync()

### PR DESCRIPTION
**Pull request by dshe**

### CODE REVIEW

**Comment by lppkarl** [comment]
@dshe Thanks for the PR 👍 It looks like we could also implement QueryTag for easier access of quote's properties 😄

**Comment by dshe** [comment]
@lppkarl Hi!
```
string  ask =          Yahoo.Symbol("C").GetJsonAsync()["C"]["ask"]; // string
dynamic ask =          Yahoo.Symbol("C").GetJsonAsync()["C"]["ask"]; // dynamic
decimal ask = (decimal)Yahoo.Symbol("C").GetJsonAsync()["C"]["ask"]; // object
```
GetJsonAsync() could return type string, dynamic, object. Returning strings (the ways it is now) requires the caller to do any parsing. Dynamic can return any type but it can be confusing and does not add much more than object. So I think returning object is probably best. The caller would need to know the data type and perform the correct cast. What do you think?

**Comment by dshe** [comment]
@lppkarl On second thought, dynamic seems most appropriate. I have updated the dev branch. Please take a look at YahooQueryAsync() and the YahooQueryAsyncTest().

**Comment by lppkarl** [comment]
@dshe I'm thinking to create a class for the json instead of using a dictionary, because it seems we no longer needs to specify the "tags" for Yahoo to process the result, and it returns a full set of data which can be parsed to a dedicated class with strict type on the values, i think it's better than the dynamic approach. How do you think?

**Comment by dshe** [comment]
Hi! Fields/tags are still important and can still be specified. If no tags
are specified, it seems that all data is returned. I have modified the
program to support both enum and string fields. The program also returns
all the Yahoo properties. Please check the dev branch.

**Comment by dshe** [comment]
Yes, Pascal case is better. I made a few more small changes.

**Pull request merged**
