### PR TITLE
Add post market fields

### PR DESCRIPTION
**Pull request by KrisSiegel**
As per #34 I added the fields necessary for after hours / pre market pricing.

Let me know if you need any further changes before merging!

### CODE REVIEW

**Comment by dshe** [comment]
Thanks for your help.

Would you please modify or comment out the failing test?

**Comment by KrisSiegel** [comment]
I took a look at the test. That test also fails in master (it was unrelated to my changes). But I believe I fixed the test (looks like it was backwards).

**Comment by dshe** [comment]
Thank you!

**Comment by KrisSiegel** [comment]
@dshe do you know when this will get published to nuget? I'm assuming it's not automated here?

**Comment by lppkarl** [comment]
@KrisSiegel & @dshe Sorry for overlooking your message, the nuget package has just been published. The new package will be available in a minute. Thanks.

**Comment by KrisSiegel** [comment]
Woohoo, thanks!

**Pull request merged**
