### PR TITLE
async improvements

### PR DESCRIPTION
**Pull request by dshe**
Async improvements and minor reorganization.

### CODE REVIEW

**Comment by dshe** [comment]
Apologies for the monster pull request.

**Comment by lppkarl** [comment]
@dshe 👍 for the PR. I will review it first 😄

**Comment by lppkarl** [comment]
@dshe by the way, would you mind I add you to the collaborator list? I mean, you could help merging & publishing new fixes to nuget when I'm busying with other things. It would be nice if you accept it 😄

**Comment by dshe** [comment]
@lppkarl Sure, you can add me as a collaborator. But don't be fooled. I am a real beginner with GitHub.

**Comment by lppkarl** [comment]
@dshe that's alright. Github is easy to use if you're familiar with git, I think you're capable on this 😄 The invitation should be sent once I added you, please accept it if you see it.

**Pull request merged**
